### PR TITLE
CI Delta Analysis task

### PR DESCRIPTION
**Pull request by tde01065**
This is the Azure DevOps task for delta analysis in the CI flow. Some things remain to implement. This will come in future releases.

### CODE REVIEW

**Comment by jumarko** [comment]
@tde01065 is this still relevant?

**Comment by tde01065** [comment]
> @tde01065 is this still relevant?

@jumarko Well.. That depends. If I'm not mistaken, you've created your own integration with Azure DevOps, rendering this obsolete. I'm still using this though. So if you want to get rid of this branch and not integrate it, then I'll move it to another repo.

**Comment by jumarko** [comment]
It's no problem to keep the branch here - but if the PR isn't going to be merged then we can close this.
Or perhaps I can merge it anyway just to have an alternative way of doing things - I guess whatever you prefer :).

**Comment by tde01065** [comment]
We might as well merge it. It is in a working state. And also, I just realized that this entire repo is specific for Azure DevOps tasks and therefore is separate from the rest of CodeScene. Hence, it probably not a problem to keep it. So please merge :)

**Review by jumarko — APPROVED** [review]

**Pull request merged**
